### ISSUE TITLE
Template fails to load textures

### ISSUE THREAD

**Issue by LordSyd** [AlmasB/FXGL-MavenGradle#2]
Following errors are thrown:

1:40:18.313 [JavaFX Application Thread] INFO  Engine               - FXGL-11.12 (11.12.2020 08.51) on WINDOWS (J:15.0.1 FX:15)
11:40:18.314 [JavaFX Application Thread] INFO  Engine               - Source code and latest versions at: https://github.com/AlmasB/FXGL
11:40:18.314 [JavaFX Application Thread] INFO  Engine               -              Join the FXGL chat at: https://gitter.im/AlmasB/FXGL
11:40:18.613 [FXGL Background Thread 1 ] WARN  FXGL.DefaultMenu     - FXGLDefaultMenu is not designed for resolutions < 800x600
11:40:18.685 [FXGL Background Thread 1 ] INFO  FXGLApplication      - FXGL initialization took: 0,224 sec
11:40:18.716 [FXGL Background Thread 1 ] WARN  FXGLAssetLoaderServi - Failed to load texture bucket.png Error: java.lang.IllegalArgumentException: Asset "/assets/textures/bucket.png" was not found!
11:40:18.732 [FXGL Background Thread 1 ] WARN  FXGLAssetLoaderServi - Failed to load music bgm.mp3 Error: java.lang.IllegalArgumentException: Asset "/assets/music/bgm.mp3" was not found!
11:40:18.735 [FXGL Background Thread 1 ] INFO  FXGLApplication      - Game initialization took: 0,019 sec
11:40:19.212 [FXGL Background Thread 2 ] INFO  UpdaterService       - Your current version:  11.12
11:40:19.212 [FXGL Background Thread 2 ] INFO  UpdaterService       - Latest stable version: 11.11
11:40:19.692 [JavaFX Application Thread] WARN  FXGLAssetLoaderServi - Failed to load texture droplet.png Error: java.lang.IllegalArgumentException: Asset "/assets/textures/droplet.png" was not found!
11:40:20.705 [JavaFX Application Thread] WARN  FXGLAssetLoaderServi - Failed to load texture droplet.png Error: java.lang.IllegalArgumentException: Asset "/assets/textures/droplet.png" was not found!
11:40:21.730 [JavaFX Application Thread] WARN  FXGLAssetLoaderServi - Failed to load texture droplet.png Error: java.lang.IllegalArgumentException: Asset "/assets/textures/droplet.png" was not found!

Game runs, but uses a placeholder texture. Found similar problems with templates while searching online, but some of the solutions I either don't understand or do not work for me, sadly.

**Comment by AlmasB** [comment]
Try right-click and rebuild on `resources` in your IDE. Sometimes, IDEs do not copy resources correctly.

**Comment by LordSyd** [comment]
Sadly did not work, error still persists.

**Comment by LordSyd** [comment]
I did a little bit of testing. If I do this:

```java
 File test = new File("src/main/assets/textures/ship5.png");

 String str = test.getAbsolutePath();

FileInputStream input = new FileInputStream(str);
Image img = new Image(input);
ImageView view = new ImageView(img);

var ship = FXGL.entityBuilder(data)

          
                .viewWithBBox(view)
                .build();
                
```
Then it works, and the image gets added correctly. As you can see from the path, I have my assets in the main folder. Put using

```java
File test = new File("src/main/resources/assets/textures/ship5.png");
```
Works also. Maybe this helps in narrowing down the error

**Comment by AlmasB** [comment]
I am not sure where the error is coming from. All asset loading code is
fully tested on CI.

Can you try running from the command line?

**Comment by LordSyd** [comment]
Please excuse the question, but I am rather new to java - What commands would I need to run? And should I run them from the terminal inside Intellij for instance?

**Comment by AlmasB** [comment]
No worries. 

1. Get [apache maven binary zip](https://maven.apache.org/download.cgi). 
2. Set `JAVA_HOME` environment variable to point to your jdk 11+. If you haven't done this before, have a look online on how to set it based on your OS.
3. Then run from the terminal (e.g. Linux terminal / Git bash) -- don't use IDE, as it will help us see where the error is coming from

```
mvn javafx:run
```

**Comment by LordSyd** [comment]
Ok, thanks for the patience. I will look into it when I have some spare time - got 3 exams upcoming in the next few days, so I am somewhat lacking in free time. 

But I am curious to get to the bottom of this, so I'll test this when I can

**Comment by LordSyd** [comment]
Got around to testing what you asked. Running the command produced a build failure:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.122 s
[INFO] Finished at: 2021-01-18T10:03:16+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'javaFX' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Daniel K\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by AlmasB** [comment]
Please can you post what command you ran and note it's case sensitive

**Comment by LordSyd** [comment]
![grafik](https://user-images.githubusercontent.com/20776219/104900478-6463a200-597c-11eb-9128-3a38af861e93.png)

Hope the screenshot helps.

**Comment by AlmasB** [comment]
Hmm, you need to run this inside the project directory.

**Comment by LordSyd** [comment]
oh... well sorry for the noob thing... will do

**Comment by LordSyd** [comment]
> 
> 
> Hmm, you need to run this inside the project directory.

Do I have to be inside src? or just inside the directory?

**Comment by AlmasB** [comment]
Inside the top-level directory (FXGL-MavenGradle), i.e. where `pom.xml` is located.

**Comment by LordSyd** [comment]
ok, was in the right place then, same error - should I post the complete output from GitBash?

**Comment by AlmasB** [comment]
yes, please. A screenshot will do

**Comment by LordSyd** [comment]
![grafik](https://user-images.githubusercontent.com/20776219/104901502-bfe25f80-597d-11eb-8bac-b08bf640197f.png)
![grafik](https://user-images.githubusercontent.com/20776219/104901550-d38dc600-597d-11eb-9729-401e8ddeb6b6.png)

**Comment by AlmasB** [comment]
Please make sure that you are using the latest pom.xml from this repository.

**Comment by LordSyd** [comment]
Updated the POM, had to change the source inside it to "14", to get further, still get this error:

![grafik](https://user-images.githubusercontent.com/20776219/104902514-1ef4a400-597f-11eb-977b-703050beb2fb.png)

**Comment by AlmasB** [comment]
Have you made any changes to the project? If so, it might be best to simply download the latest copy of this directory and run maven.

**Comment by AlmasB** [comment]
Here's "reference" output:

```
Almas@Ascension MINGW64 ~/almas_workspace/java/FXGL-MavenGradle (master)
$ mvn -v
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T19:33:14+01:00)
Maven home: C:\Users\Almas\almas_program_files\apache-maven
Java version: 14.0.2, vendor: Oracle Corporation, runtime: C:\Users\Almas\almas_program_files\JDK14
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Almas@Ascension MINGW64 ~/almas_workspace/java/FXGL-MavenGradle (master)
$ mvn javafx:run
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< com.almasb:Drop >---------------------------
[INFO] Building Drop 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> javafx-maven-plugin:0.0.5:run (default-cli) > process-classes @ Drop >>>
[INFO]
[INFO] --- kotlin-maven-plugin:1.4.10:compile (compile) @ Drop ---
[WARNING] No sources found skipping Kotlin compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Drop ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ Drop ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\Users\Almas\almas_workspace\java\FXGL-MavenGradle\target\classes
[INFO]
[INFO] <<< javafx-maven-plugin:0.0.5:run (default-cli) < process-classes @ Drop <<<
[INFO]
[INFO]
[INFO] --- javafx-maven-plugin:0.0.5:run (default-cli) @ Drop ---
10:22:41.923 [JavaFX Application Thread] INFO  Engine               - FXGL-11.12 (11.12.2020 08.51) on WINDOWS (J:14.0.2 FX:15)
10:22:41.924 [JavaFX Application Thread] INFO  Engine               - Source code and latest versions at: https://github.com/AlmasB/FXGL
10:22:41.924 [JavaFX Application Thread] INFO  Engine               -              Join the FXGL chat at: https://gitter.im/AlmasB/FXGL
10:22:42.503 [FXGL Background Thread 1 ] WARN  FXGL.DefaultMenu     - FXGLDefaultMenu is not designed for resolutions < 800x600
10:22:42.631 [FXGL Background Thread 1 ] INFO  FXGLApplication      - FXGL initialization took: 0.402 sec
10:22:43.390 [FXGL Background Thread 4 ] INFO  FXGLApplication      - Game initialization took: 0.675 sec
10:22:43.529 [FXGL Background Thread 2 ] INFO  UpdaterService       - Your current version:  11.12
10:22:43.529 [FXGL Background Thread 2 ] INFO  UpdaterService       - Latest stable version: 11.11
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.174 s
[INFO] Finished at: 2021-01-18T10:22:46Z
[INFO] ------------------------------------------------------------------------

Almas@Ascension MINGW64 ~/almas_workspace/java/FXGL-MavenGradle (master)
$

```

**Comment by LordSyd** [comment]
Okay, did some testing.

First, yes I did use this template to develop my project, so I added some things.

I pulled a fresh copy of the repo just now - maven runs without any issues, gradle still hast the texture loading problem.

Edit: Did some further testing, modified the POM to fit my project (was pointing at wrong main class).
Now, Maven compiles without errors finding all assets, gradle still, as stated above cannot find any assets

**Comment by LordSyd** [comment]
Solved the issue... A malformed modul_info.java was causing gradle to make problems. Solved it by deleting it - brutal, but it worked. Now gradle run works without error, and finds all assets. Could you just tell me if this module info file is needed, and how I would need to configure it correctly?

```java
/**
 * @author Almas Baimagambetov (almaslvl@gmail.com)
 */
open module drop.main {  //<-- what needs to be but there? Name of my main class? or something else?
    requires com.almasb.fxgl.all;
    requires annotations;
    requires javafx.media;
}
```

if not, this issue is resolved. :)

**Comment by AlmasB** [comment]
Thanks for letting me know.

module-info is needed for generating jlinked platform images for deployment. The one provided should be fine, as it works with maven. Will investigate the gradle build later.

**Comment by LordSyd** [comment]
I renamed the package and main Class, so maybe the name of my class or package causes the problem. If you need any more info let me know!

**Comment by AlmasB** [comment]
Should work now. If you'd like to test it out, please get a fresh copy of the repo and run with gradle instructions in README

**Comment by LordSyd** [comment]
updated the repo that I had local, works fine now.

I think that I botched something when using this repo as a starting point for my project. By renaming the Main Class and the package gradle got very unhappy - I thought I changed all the importand config files, but the module_info.java file continued to cause a problem. Still do not know what would be the correct way to configure this file.

In any case, the issue is solved, If there is nothing else you want me to test you can close this issue. Thanks for your patience!

**Comment by AlmasB** [comment]
I often encounter issues with gradle myself, which is why I prefer maven. Good to know the updated gradle build works fine now. Thanks.
